Fix configure.py issue with --clang_path.
If --clang_path is passed a symlink, an error would occur when building C++ files that had includes from the standard library. E.g., a possible error was:

ERROR: /root/.cache/bazel/_bazel_root/e4ab50d61a21943a819d1e092972a817/external/zlib/BUILD.bazel:5:11: Compiling zutil.c [for tool] failed: undeclared inclusion(s) in rule '@zlib//:zlib':
this rule is missing dependency declarations for the following files included by 'zutil.c':
  '/usr/lib/clang/17/include/stddef.h'
  '/usr/lib/clang/17/include/__stddef_max_align_t.h'
  '/usr/lib/clang/17/include/limits.h'
  '/usr/lib/clang/17/include/stdarg.h'

The clang on the PATH, such as /usr/bin/clang-17, is usually symlinked to a file such as /usr/lib/llvm-17/bin/clang, so this would typically cause issues when building with --clang_path.

The issue is that bazel gives such errors when compiled with a symlinked clang. Without --clang_path, we resolved symlinks, but not with --clang_path. This change also resolves symlinks with --clang_path.

PiperOrigin-RevId: 635971435